packages:
  - core
  - service
  - web

allowBuilds:
  '@google/genai': false
  '@nkzw/mdx-editor': true
  '@swc/core': true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  native-keymap: true
  node-pty: true
  protobufjs: false
  sharp: true
  workerd: true
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - '@nkzw/*'
  - '@voidzero-dev/vite-plus-core@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de'
  - '@voidzero-dev/vite-plus-darwin-x64@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de'
  - vite-plus@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de
  vite-plus: 0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de
  vitest: 4.1.11
nodeLinker: hoisted
onlyBuiltDependencies:
  - '@nkzw/mdx-editor'
  - '@swc/core'
  - electron
  - electron-winstaller
  - unrs-resolver
overrides:
  extract-zip>yauzl: ^3.4.0
  vite@*: 'catalog:'
  vitest@*: 'catalog:'
patchedDependencies:
  native-keymap@3.3.9: patches/native-keymap@3.3.9.patch
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
